//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couple
    {
        public int CouplesID { get; set; }
        public string Partner { get; set; }
        public int ProID { get; set; }
        public int HeatID { get; set; }
        public string Number { get; set; }
        public int DanceLevelID { get; set; }
        public int CouplesComboID { get; set; }
        public int DanceTypeID { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual DanceLevel DanceLevel { get; set; }
        public virtual DanceType DanceType { get; set; }
        public virtual Heat Heat { get; set; }
        public virtual Pro Pro { get; set; }
    }
}
